// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aylabvlrgscyqpgcjrux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bGFidmxyZ3NjeXFwZ2NqcnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc3NzcxMzksImV4cCI6MjA0MzM1MzEzOX0.9912jR9JALl45VDeuyW-0klGQ1p1f68x9jaw5KCCEYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);